// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Approval: typeof import('./src/components/approval/box-approval/Approval.vue')['default']
    ApprovalIquiry: typeof import('./src/components/approval/ApprovalIquiry.vue')['default']
    ApprovalTable: typeof import('./src/components/approval/ApprovalTable.vue')['default']
    BoxApprovalLine: typeof import('./src/components/approval/BoxApprovalLine.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    GroupButton: typeof import('./src/components/approval/GroupButton.vue')['default']
    NewApprover: typeof import('./src/components/approval/box-approval/NewApprover.vue')['default']
    Preloader: typeof import('./src/components/modals/Preloader.vue')['default']
    PushDetailsPage: typeof import('./src/components/PushDetailsPage.vue')['default']
    PushPage: typeof import('./src/components/PushPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
